[{"name":"result_flow","qualifiedName":"result_flow","href":"result_flow","kind":9,"packageRank":0,"desc":"Result Flow is a Dart libarary that allows handling\nasynchronous and synchronous operations with a functional approach."},{"name":"DomainError","qualifiedName":"result_flow.DomainError","href":"result_flow/DomainError-class.html","kind":3,"packageRank":0,"desc":"A class that can be used to represent a domain specific errors like invalid\ninternal operations or operations not following specific business rules.","enclosedBy":{"name":"result_flow","kind":9,"href":"result_flow"}},{"name":"DomainError","qualifiedName":"result_flow.DomainError.DomainError","href":"result_flow/DomainError/DomainError.html","kind":2,"packageRank":0,"desc":"","enclosedBy":{"name":"DomainError","kind":3,"href":"result_flow/DomainError-class.html"}},{"name":"FutureResult","qualifiedName":"result_flow.FutureResult","href":"result_flow/FutureResult.html","kind":21,"packageRank":0,"desc":"","enclosedBy":{"name":"result_flow","kind":9,"href":"result_flow"}},{"name":"FutureResultRunAfter","qualifiedName":"result_flow.FutureResultRunAfter","href":"result_flow/FutureResultRunAfter.html","kind":6,"packageRank":0,"desc":"Extension methods for FutureResult to chain operations.","enclosedBy":{"name":"result_flow","kind":9,"href":"result_flow"}},{"name":"continueWith","qualifiedName":"result_flow.FutureResultRunAfter.continueWith","href":"result_flow/FutureResultRunAfter/continueWith.html","kind":10,"overriddenDepth":0,"packageRank":0,"desc":"Asynchronously transforms the data of a successful result\nusing the after callback.","enclosedBy":{"name":"FutureResultRunAfter","kind":6,"href":"result_flow/FutureResultRunAfter.html"}},{"name":"handle","qualifiedName":"result_flow.FutureResultRunAfter.handle","href":"result_flow/FutureResultRunAfter/handle.html","kind":10,"overriddenDepth":0,"packageRank":0,"desc":"Asynchronously handles an error result by\nexecuting the onError callback.","enclosedBy":{"name":"FutureResultRunAfter","kind":6,"href":"result_flow/FutureResultRunAfter.html"}},{"name":"handleAsync","qualifiedName":"result_flow.FutureResultRunAfter.handleAsync","href":"result_flow/FutureResultRunAfter/handleAsync.html","kind":10,"overriddenDepth":0,"packageRank":0,"desc":"Asynchronously handles an error result by executing\nthe onError callback.","enclosedBy":{"name":"FutureResultRunAfter","kind":6,"href":"result_flow/FutureResultRunAfter.html"}},{"name":"mapToAsync","qualifiedName":"result_flow.FutureResultRunAfter.mapToAsync","href":"result_flow/FutureResultRunAfter/mapToAsync.html","kind":10,"overriddenDepth":0,"packageRank":0,"desc":"Asynchronously transforms the data of a successful result\nusing the after callback.","enclosedBy":{"name":"FutureResultRunAfter","kind":6,"href":"result_flow/FutureResultRunAfter.html"}},{"name":"NetworkError","qualifiedName":"result_flow.NetworkError","href":"result_flow/NetworkError-class.html","kind":3,"packageRank":0,"desc":"A class representing a network error.\nThis class extends the ResultError class and provides additional\nfunctionality for handling network-related errors.","enclosedBy":{"name":"result_flow","kind":9,"href":"result_flow"}},{"name":"NetworkError","qualifiedName":"result_flow.NetworkError.NetworkError","href":"result_flow/NetworkError/NetworkError.html","kind":2,"packageRank":0,"desc":"","enclosedBy":{"name":"NetworkError","kind":3,"href":"result_flow/NetworkError-class.html"}},{"name":"statusCode","qualifiedName":"result_flow.NetworkError.statusCode","href":"result_flow/NetworkError/statusCode.html","kind":16,"overriddenDepth":0,"packageRank":0,"desc":"","enclosedBy":{"name":"NetworkError","kind":3,"href":"result_flow/NetworkError-class.html"}},{"name":"toString","qualifiedName":"result_flow.NetworkError.toString","href":"result_flow/NetworkError/toString.html","kind":10,"overriddenDepth":2,"packageRank":0,"desc":"A string representation of this object.","enclosedBy":{"name":"NetworkError","kind":3,"href":"result_flow/NetworkError-class.html"}},{"name":"Result","qualifiedName":"result_flow.Result","href":"result_flow/Result-class.html","kind":3,"packageRank":0,"desc":"A class that represents the result of an operation. It can be either a\nsuccess using ResultWithData or an error using ResultWithError.","enclosedBy":{"name":"result_flow","kind":9,"href":"result_flow"}},{"name":"Result.error","qualifiedName":"result_flow.Result.Result.error","href":"result_flow/Result/Result.error.html","kind":2,"packageRank":0,"desc":"","enclosedBy":{"name":"Result","kind":3,"href":"result_flow/Result-class.html"}},{"name":"Result.exception","qualifiedName":"result_flow.Result.Result.exception","href":"result_flow/Result/Result.exception.html","kind":2,"packageRank":0,"desc":"","enclosedBy":{"name":"Result","kind":3,"href":"result_flow/Result-class.html"}},{"name":"Result.success","qualifiedName":"result_flow.Result.Result.success","href":"result_flow/Result/Result.success.html","kind":2,"packageRank":0,"desc":"","enclosedBy":{"name":"Result","kind":3,"href":"result_flow/Result-class.html"}},{"name":"continueWith","qualifiedName":"result_flow.Result.continueWith","href":"result_flow/Result/continueWith.html","kind":10,"overriddenDepth":0,"packageRank":0,"desc":"Asynchronously transforms the data of a successful result using\nthe after callback. If the result is an error, or if an exception\noccurs in the after callback, it returns a new error result.","enclosedBy":{"name":"Result","kind":3,"href":"result_flow/Result-class.html"}},{"name":"data","qualifiedName":"result_flow.Result.data","href":"result_flow/Result/data.html","kind":16,"overriddenDepth":0,"packageRank":0,"desc":"Returns the data if the result is a success, otherwise returns null.","enclosedBy":{"name":"Result","kind":3,"href":"result_flow/Result-class.html"}},{"name":"dataOrThrow","qualifiedName":"result_flow.Result.dataOrThrow","href":"result_flow/Result/dataOrThrow.html","kind":16,"overriddenDepth":0,"packageRank":0,"desc":"Returns the data if the result is a success, otherwise throws the error.","enclosedBy":{"name":"Result","kind":3,"href":"result_flow/Result-class.html"}},{"name":"error","qualifiedName":"result_flow.Result.error","href":"result_flow/Result/error.html","kind":16,"overriddenDepth":0,"packageRank":0,"desc":"Returns the error if the result is an error, otherwise returns null.","enclosedBy":{"name":"Result","kind":3,"href":"result_flow/Result-class.html"}},{"name":"getOrElse","qualifiedName":"result_flow.Result.getOrElse","href":"result_flow/Result/getOrElse.html","kind":10,"overriddenDepth":0,"packageRank":0,"desc":"Returns the data if the result is a success,\notherwise returns the defaultValue.","enclosedBy":{"name":"Result","kind":3,"href":"result_flow/Result-class.html"}},{"name":"handle","qualifiedName":"result_flow.Result.handle","href":"result_flow/Result/handle.html","kind":10,"overriddenDepth":0,"packageRank":0,"desc":"Handles an error result by executing the onError callback.\nIf the result is a success, it returns the original result.\nIf an exception occurs in the onError callback,\nit returns a new error result.","enclosedBy":{"name":"Result","kind":3,"href":"result_flow/Result-class.html"}},{"name":"handleAsync","qualifiedName":"result_flow.Result.handleAsync","href":"result_flow/Result/handleAsync.html","kind":10,"overriddenDepth":0,"packageRank":0,"desc":"Asynchronously handles an error result by executing\nthe onError callback. If the result is a success, it returns\nthe original result. If an exception occurs in the onError callback,\nit returns a new error result.","enclosedBy":{"name":"Result","kind":3,"href":"result_flow/Result-class.html"}},{"name":"isError","qualifiedName":"result_flow.Result.isError","href":"result_flow/Result/isError.html","kind":16,"overriddenDepth":0,"packageRank":0,"desc":"","enclosedBy":{"name":"Result","kind":3,"href":"result_flow/Result-class.html"}},{"name":"isSuccess","qualifiedName":"result_flow.Result.isSuccess","href":"result_flow/Result/isSuccess.html","kind":16,"overriddenDepth":0,"packageRank":0,"desc":"","enclosedBy":{"name":"Result","kind":3,"href":"result_flow/Result-class.html"}},{"name":"mapTo","qualifiedName":"result_flow.Result.mapTo","href":"result_flow/Result/mapTo.html","kind":10,"overriddenDepth":0,"packageRank":0,"desc":"Transforms the data of a successful result using the after callback.\nIf the result is an error, or if an exception occurs in\nthe after callback, it returns a new error result.","enclosedBy":{"name":"Result","kind":3,"href":"result_flow/Result-class.html"}},{"name":"on","qualifiedName":"result_flow.Result.on","href":"result_flow/Result/on.html","kind":10,"overriddenDepth":0,"packageRank":0,"desc":"on is a method that allows you to handle the result of an operation\nby providing two callbacks:","enclosedBy":{"name":"Result","kind":3,"href":"result_flow/Result-class.html"}},{"name":"onAsync","qualifiedName":"result_flow.Result.onAsync","href":"result_flow/Result/onAsync.html","kind":10,"overriddenDepth":0,"packageRank":0,"desc":"onAsync is a method that allows you to handle the result of an\nasynchronous operation by providing two callbacks:","enclosedBy":{"name":"Result","kind":3,"href":"result_flow/Result-class.html"}},{"name":"onError","qualifiedName":"result_flow.Result.onError","href":"result_flow/Result/onError.html","kind":10,"overriddenDepth":0,"packageRank":0,"desc":"Executes the error callback if the result is an error.\nReturns the result of the error callback or null if the result is a\nsuccess or an exception occurs.","enclosedBy":{"name":"Result","kind":3,"href":"result_flow/Result-class.html"}},{"name":"onSuccess","qualifiedName":"result_flow.Result.onSuccess","href":"result_flow/Result/onSuccess.html","kind":10,"overriddenDepth":0,"packageRank":0,"desc":"Executes the success callback if the result is a success.\nReturns the result of the success callback or null if the result is\nan error or an exception occurs.","enclosedBy":{"name":"Result","kind":3,"href":"result_flow/Result-class.html"}},{"name":"safeRun","qualifiedName":"result_flow.Result.safeRun","href":"result_flow/Result/safeRun.html","kind":10,"overriddenDepth":0,"packageRank":0,"desc":"A helper method to wraps a synchronous operation that can throw an\nexception or return a result. If the operation throws an exception,\nit will be caught and wrapped in a ResultError or UnknownError.\nIf the operation returns a result, it will be wrapped in a\nResultWithData instance.","enclosedBy":{"name":"Result","kind":3,"href":"result_flow/Result-class.html"}},{"name":"safeRunAsync","qualifiedName":"result_flow.Result.safeRunAsync","href":"result_flow/Result/safeRunAsync.html","kind":10,"overriddenDepth":0,"packageRank":0,"desc":"A helper method to wraps an asynchronous operation that can throw an\nexception or return a result. If the operation throws an exception,\nit will be caught and wrapped in a ResultError or UnknownError.\nIf the operation returns a result, it will be wrapped in a\nResultWithData instance.","enclosedBy":{"name":"Result","kind":3,"href":"result_flow/Result-class.html"}},{"name":"ResultError","qualifiedName":"result_flow.ResultError","href":"result_flow/ResultError-class.html","kind":3,"packageRank":0,"desc":"Base class for all errors that allow customization either through\nunique error codes or by extending the base error class.","enclosedBy":{"name":"result_flow","kind":9,"href":"result_flow"}},{"name":"ResultError","qualifiedName":"result_flow.ResultError.ResultError","href":"result_flow/ResultError/ResultError.html","kind":2,"packageRank":0,"desc":"","enclosedBy":{"name":"ResultError","kind":3,"href":"result_flow/ResultError-class.html"}},{"name":"code","qualifiedName":"result_flow.ResultError.code","href":"result_flow/ResultError/code.html","kind":16,"overriddenDepth":0,"packageRank":0,"desc":"","enclosedBy":{"name":"ResultError","kind":3,"href":"result_flow/ResultError-class.html"}},{"name":"message","qualifiedName":"result_flow.ResultError.message","href":"result_flow/ResultError/message.html","kind":16,"overriddenDepth":0,"packageRank":0,"desc":"","enclosedBy":{"name":"ResultError","kind":3,"href":"result_flow/ResultError-class.html"}},{"name":"toString","qualifiedName":"result_flow.ResultError.toString","href":"result_flow/ResultError/toString.html","kind":10,"overriddenDepth":1,"packageRank":0,"desc":"A string representation of this object.","enclosedBy":{"name":"ResultError","kind":3,"href":"result_flow/ResultError-class.html"}},{"name":"ResultMapperCallback","qualifiedName":"result_flow.ResultMapperCallback","href":"result_flow/ResultMapperCallback.html","kind":21,"packageRank":0,"desc":"","enclosedBy":{"name":"result_flow","kind":9,"href":"result_flow"}},{"name":"ResultMapperCallbackAsync","qualifiedName":"result_flow.ResultMapperCallbackAsync","href":"result_flow/ResultMapperCallbackAsync.html","kind":21,"packageRank":0,"desc":"","enclosedBy":{"name":"result_flow","kind":9,"href":"result_flow"}},{"name":"ResultStream","qualifiedName":"result_flow.ResultStream","href":"result_flow/ResultStream.html","kind":21,"packageRank":0,"desc":"","enclosedBy":{"name":"result_flow","kind":9,"href":"result_flow"}},{"name":"ResultWithData","qualifiedName":"result_flow.ResultWithData","href":"result_flow/ResultWithData-class.html","kind":3,"packageRank":0,"desc":"","enclosedBy":{"name":"result_flow","kind":9,"href":"result_flow"}},{"name":"data","qualifiedName":"result_flow.ResultWithData.data","href":"result_flow/ResultWithData/data.html","kind":16,"overriddenDepth":0,"packageRank":0,"desc":"Returns the data if the result is a success, otherwise returns null.","enclosedBy":{"name":"ResultWithData","kind":3,"href":"result_flow/ResultWithData-class.html"}},{"name":"ResultWithError","qualifiedName":"result_flow.ResultWithError","href":"result_flow/ResultWithError-class.html","kind":3,"packageRank":0,"desc":"","enclosedBy":{"name":"result_flow","kind":9,"href":"result_flow"}},{"name":"error","qualifiedName":"result_flow.ResultWithError.error","href":"result_flow/ResultWithError/error.html","kind":16,"overriddenDepth":0,"packageRank":0,"desc":"Returns the error if the result is an error, otherwise returns null.","enclosedBy":{"name":"ResultWithError","kind":3,"href":"result_flow/ResultWithError-class.html"}},{"name":"UnknownError","qualifiedName":"result_flow.UnknownError","href":"result_flow/UnknownError-class.html","kind":3,"packageRank":0,"desc":"A class used as a generic error and a wrapper to uncaught exceptions.","enclosedBy":{"name":"result_flow","kind":9,"href":"result_flow"}},{"name":"UnknownError","qualifiedName":"result_flow.UnknownError.UnknownError","href":"result_flow/UnknownError/UnknownError.html","kind":2,"packageRank":0,"desc":"","enclosedBy":{"name":"UnknownError","kind":3,"href":"result_flow/UnknownError-class.html"}},{"name":"ValidationError","qualifiedName":"result_flow.ValidationError","href":"result_flow/ValidationError-class.html","kind":3,"packageRank":0,"desc":"A class representing a validation error. This class allows for form\nvalidation and provides a way to represent the details of the validation\nerror for each field.","enclosedBy":{"name":"result_flow","kind":9,"href":"result_flow"}},{"name":"ValidationError","qualifiedName":"result_flow.ValidationError.ValidationError","href":"result_flow/ValidationError/ValidationError.html","kind":2,"packageRank":0,"desc":"","enclosedBy":{"name":"ValidationError","kind":3,"href":"result_flow/ValidationError-class.html"}},{"name":"ValidationError.fromField","qualifiedName":"result_flow.ValidationError.ValidationError.fromField","href":"result_flow/ValidationError/ValidationError.fromField.html","kind":2,"packageRank":0,"desc":"","enclosedBy":{"name":"ValidationError","kind":3,"href":"result_flow/ValidationError-class.html"}},{"name":"addField","qualifiedName":"result_flow.ValidationError.addField","href":"result_flow/ValidationError/addField.html","kind":10,"overriddenDepth":0,"packageRank":0,"desc":"","enclosedBy":{"name":"ValidationError","kind":3,"href":"result_flow/ValidationError-class.html"}},{"name":"addFields","qualifiedName":"result_flow.ValidationError.addFields","href":"result_flow/ValidationError/addFields.html","kind":10,"overriddenDepth":0,"packageRank":0,"desc":"","enclosedBy":{"name":"ValidationError","kind":3,"href":"result_flow/ValidationError-class.html"}},{"name":"details","qualifiedName":"result_flow.ValidationError.details","href":"result_flow/ValidationError/details.html","kind":16,"overriddenDepth":0,"packageRank":0,"desc":"","enclosedBy":{"name":"ValidationError","kind":3,"href":"result_flow/ValidationError-class.html"}},{"name":"getField","qualifiedName":"result_flow.ValidationError.getField","href":"result_flow/ValidationError/getField.html","kind":10,"overriddenDepth":0,"packageRank":0,"desc":"","enclosedBy":{"name":"ValidationError","kind":3,"href":"result_flow/ValidationError-class.html"}},{"name":"toString","qualifiedName":"result_flow.ValidationError.toString","href":"result_flow/ValidationError/toString.html","kind":10,"overriddenDepth":2,"packageRank":0,"desc":"A string representation of this object.","enclosedBy":{"name":"ValidationError","kind":3,"href":"result_flow/ValidationError-class.html"}},{"name":"ValidationErrorFields","qualifiedName":"result_flow.ValidationErrorFields","href":"result_flow/ValidationErrorFields-class.html","kind":3,"packageRank":0,"desc":"A class representing a validation error for a specific field.\nThis class is used to represent the details of the validation error\nfor a specific field in the form.","enclosedBy":{"name":"result_flow","kind":9,"href":"result_flow"}},{"name":"ValidationErrorFields","qualifiedName":"result_flow.ValidationErrorFields.ValidationErrorFields","href":"result_flow/ValidationErrorFields/ValidationErrorFields.html","kind":2,"packageRank":0,"desc":"","enclosedBy":{"name":"ValidationErrorFields","kind":3,"href":"result_flow/ValidationErrorFields-class.html"}},{"name":"ValidationErrorFields.fromField","qualifiedName":"result_flow.ValidationErrorFields.ValidationErrorFields.fromField","href":"result_flow/ValidationErrorFields/ValidationErrorFields.fromField.html","kind":2,"packageRank":0,"desc":"","enclosedBy":{"name":"ValidationErrorFields","kind":3,"href":"result_flow/ValidationErrorFields-class.html"}},{"name":"field","qualifiedName":"result_flow.ValidationErrorFields.field","href":"result_flow/ValidationErrorFields/field.html","kind":16,"overriddenDepth":0,"packageRank":0,"desc":"","enclosedBy":{"name":"ValidationErrorFields","kind":3,"href":"result_flow/ValidationErrorFields-class.html"}},{"name":"message","qualifiedName":"result_flow.ValidationErrorFields.message","href":"result_flow/ValidationErrorFields/message.html","kind":16,"overriddenDepth":0,"packageRank":0,"desc":"","enclosedBy":{"name":"ValidationErrorFields","kind":3,"href":"result_flow/ValidationErrorFields-class.html"}},{"name":"unknownErrorCode","qualifiedName":"result_flow.unknownErrorCode","href":"result_flow/unknownErrorCode-constant.html","kind":19,"packageRank":0,"desc":"","enclosedBy":{"name":"result_flow","kind":9,"href":"result_flow"}},{"name":"validationErrorCode","qualifiedName":"result_flow.validationErrorCode","href":"result_flow/validationErrorCode-constant.html","kind":19,"packageRank":0,"desc":"","enclosedBy":{"name":"result_flow","kind":9,"href":"result_flow"}}]
